telegram.bot.token=7460878562:AAHDypbxL-DMolzBtYkNSImrkAe-dqudt9w
telegram.bot.username=SignForMasters_bot

app.admin.ids=1108777017

app.timezone=Europe/Moscow
app.slot.duration.minutes=30

# --- Datasource (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/tg_nails
spring.datasource.username=postgres
spring.datasource.password=gjnc!47745hdF
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.pool-name=tg-nails-pool

# --- Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.out-of-order=false